server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    function:
      definition: consumeResource; getById
    stream:
      bindings:
        saveResource-out-0:
          destination: gateway.resource.save
        openResource-out-0:
          destination: gateway.resource.open
        registerResource-out-0:
          destination: gateway.resource.register
        consumeResource-in-0:
          destination: control.resource.response
          group: gateway
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus